### ISSUE TITLE
Bad filename

### ISSUE THREAD

**Issue by castillop** [Sebasinos/ProyectoPET#2]
File "cal_dacay.py" contains function "cal_decay.py". Typo?

**Comment by Sebasinos** [comment]
se actualiza documentación del archivo cal_decay.py - 
return type Float-

**Comment by Sebasinos** [comment]
def cal_decay(dose_act,minut_decay): #receives str type 
    dose_act=float(dose_act) #transform float
    des_fluor =float(109.771) #re-transform float 
    minutos=float(minut_decay)#transfrom float

**Comment by Sebasinos** [comment]
rename to file name: cal_dacay ext.py = cal_decay.py
